/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorEstudiante;
import modelo.Estudiante;
import modelo.RegistroEstudiantes;

/**
 *
 * @author ronald
 */
public class GUIAdminEstudiante extends GUIMantenimiento {

    private RegistroEstudiantes registro;
    private GUIMantenimiento gUIMantenimiento;
    
    public void setRegistroEstudiantes(RegistroEstudiantes registro){
         this.registro=registro;  
         gUIMantenimiento = new GUIMantenimiento();
    }
    
    public void init(){
        setDatosTabla(registro.getMatrizEstudiantes(), Estudiante.getEtiquetasAtributos());
        setCamposClave(Estudiante.getEtiquetasAtributos());
        ManejadorEstudiante manejadorEstudiante=new ManejadorEstudiante(registro,this, gUIMantenimiento);
        setControlador(manejadorEstudiante); 
        setTitle("Mantenimiento de \"Estudiantes\"");
    }
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
