/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorMenu;
import modelo.RegistroEstudiantes;
import javax.swing.JFrame;
import modelo.RegistroCursos;
import modelo.RegistroMatricula;

/**
 * TAREA #3 UCR-Programación II-2015
 *
 * @author Bryan Marín Quesada(B23907)
 */
public class Menu extends JFrame {

    public static final String ITEM_ESTUDIANTE = "Estudiante", ITEM_CURSO = "Curso", ITEM_MATRICULA = "Matrícula";
    private final RegistroEstudiantes registroEstudiantes;
    private final RegistroCursos registroCursos;
    private final ManejadorMenu manejadorMenu;
    private final RegistroMatricula registroMatricula;

    public Menu() {
        initComponents();
        registroEstudiantes = new RegistroEstudiantes();
        registroCursos = new RegistroCursos();
        registroMatricula = new RegistroMatricula();
        manejadorMenu = new ManejadorMenu(registroEstudiantes, registroCursos, registroMatricula);
        setActionCommand();
        setManejador();
        setLocationRelativeTo(this);
    }

    public void setManejador() {
        jmiEstudiante.addActionListener(manejadorMenu);
        jmiCurso.addActionListener(manejadorMenu);
        jmiMatricula.addActionListener(manejadorMenu);
        jmiRE.addActionListener(manejadorMenu);
        jmiRC.addActionListener(manejadorMenu);
        jmiM.addActionListener(manejadorMenu);
    }

    public void setActionCommand() {
        jmiCurso.setActionCommand(ITEM_CURSO);
        jmiEstudiante.setActionCommand(ITEM_ESTUDIANTE);
        jmiMatricula.setActionCommand(ITEM_MATRICULA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jmAdministrar = new javax.swing.JMenu();
        jmiEstudiante = new javax.swing.JMenuItem();
        jmiCurso = new javax.swing.JMenuItem();
        jmiMatricula = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmiRE = new javax.swing.JMenuItem();
        jmiM = new javax.swing.JMenuItem();
        jmiRC = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Matrícula");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book.jpg"))); // NOI18N

        barraMenu.setBackground(new java.awt.Color(255, 255, 255));
        barraMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 255)));

        jmAdministrar.setText("Administrar");

        jmiEstudiante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmiEstudiante.setBackground(new java.awt.Color(153, 153, 255));
        jmiEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/people.png"))); // NOI18N
        jmiEstudiante.setText("Estudiante");
        jmAdministrar.add(jmiEstudiante);

        jmiCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiCurso.setBackground(new java.awt.Color(255, 255, 255));
        jmiCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/enroll.png"))); // NOI18N
        jmiCurso.setText("Curso");
        jmAdministrar.add(jmiCurso);

        jmiMatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmiMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student.png"))); // NOI18N
        jmiMatricula.setText("Matricula");
        jmAdministrar.add(jmiMatricula);

        barraMenu.add(jmAdministrar);

        jmReportes.setText("Reportes");

        jmiRE.setText("Registro Estudiantes");
        jmReportes.add(jmiRE);

        jmiM.setText("Registro Matrícula");
        jmiM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMActionPerformed(evt);
            }
        });
        jmReportes.add(jmiM);

        jmiRC.setText("Registro Cursos");
        jmiRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRCActionPerformed(evt);
            }
        });
        jmReportes.add(jmiRC);

        barraMenu.add(jmReportes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMActionPerformed

    private void jmiRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiRCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jmAdministrar;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuItem jmiCurso;
    private javax.swing.JMenuItem jmiEstudiante;
    private javax.swing.JMenuItem jmiM;
    private javax.swing.JMenuItem jmiMatricula;
    private javax.swing.JMenuItem jmiRC;
    private javax.swing.JMenuItem jmiRE;
    // End of variables declaration//GEN-END:variables
}
