/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Curso;

/**
 *
 * @author Bryan
 */
public class PanelCurso extends javax.swing.JPanel {

    /**
     * Creates new form PanelCurso
     */
    public PanelCurso() {
        initComponents();
    }
    
    public Curso getCurso(){
        return new Curso(jtNombre.getText(), jtSiglas.getText(), jtCreditos.getText());
    }
    
    public boolean getStateOfJTextArea(){
        if(!jtNombre.getText().equals("") && !jtSiglas.getText().equals("") && !jtCreditos.getText().equals("")){
            return true;
        }
        return false;
    }
    
    public void clean(){
        jtCreditos.setText("");
        jtNombre.setText("");
        jtSiglas.setText("");
        
    }
    
    public void setText(String nombre, String siglas, String creditos){
        jtNombre.setText(nombre);
        jtSiglas.setText(siglas);
        jtCreditos.setText(creditos);
    }
    
    public void setEditable(int index){
        if(index==1){
            jtSiglas.setEditable(true);
            jtSiglas.setEnabled(true);
        }
        else{
            jtSiglas.setEditable(false);
            jtSiglas.setEnabled(false);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNombre = new javax.swing.JLabel();
        jlSiglas = new javax.swing.JLabel();
        jlCreditos = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtSiglas = new javax.swing.JTextField();
        jtCreditos = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 255));

        jlNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlNombre.setText("Nombre: ");

        jlSiglas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlSiglas.setText("Siglas: ");

        jlCreditos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlCreditos.setText("Créditos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCreditos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombre)
                            .addComponent(jlSiglas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSiglas)
                    .addComponent(jtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCreditos)
                    .addComponent(jtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCreditos;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlSiglas;
    private javax.swing.JTextField jtCreditos;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtSiglas;
    // End of variables declaration//GEN-END:variables
}
